config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :public_folders
    root 'folders#index'
    #root 'session#login'
    get 'session/login'
    get 'session/logout'
    post 'session/create'
    resources :users
    resources :folders
    resources :tasks
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/session_controller.rb
# frozen_string_literal: true

# Session Controller
class SessionController < ApplicationController
  skip_before_action :require_login, only: %i[login create]
  def login; end

  def create
    user = User.find_by_username(params[:username])
    if user&.authenticate(params[:password])
      sign_in user
      redirect_to root_path
    else
      flash[:notice] = if user.nil?
                         t('no_user')
                       else
                         t('wrong_pass')
                       end
      p flash[:notice]
      redirect_to session_login_path
    end
  end

  def logout
    sign_out
    redirect_to session_login_path
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 7.days }
    # signed шифрует id пользователя, добавляем срок годности куки, чтобы пользователя не выкидывало во время сессии
    @current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
    # ||= <=> @current_user = User.find if @current_user.nil?
  end
end

app/views/session/login.html.erb
<div id="animated-bg" class="d-inline-flex flex-column" style="width: 100%; height: 100vh; overflow: auto">
  <div class="header" style="position: fixed; width: 100%; top: 0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-2" style="height: 125%">
      <div class="container-fluid">
        <img src="https://findicons.com/files/icons/732/snow_leopard/256/folder_folder.png" alt="Logo" style="width: 30px; height: 30px; margin-right: 10px">
        <a class="navbar-brand"><%= t 'login' %></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'EN', root_path(locale: :en), class: "nav-link mx-2" %>
            </li>
            <li class="nav-item">
              <%= link_to 'RU', root_path(locale: :ru), class: "nav-link mx-2" %>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto ">
            <li class="nav-item">
              <a class="nav-link mx-2" aria-current="page" href="/<%=locale%>/session/login"><%= t 'my_tasks' %></a>
            </li>
            <li class="nav-item">
              <%= link_to t("account"), "/#{locale}/session/login" , class: "nav-link mx-2 active"%>
            </li>
            <li class="nav-item">
              <%= link_to t("logout"), session_logout_path, class: "nav-link mx-2" %>
            </li>
          </ul>
        </div> 
      </div>
    </nav>
  </div>

  <div class="row d-flex justify-content-center" style="width: 100%; padding-top: 80px">
    <div class="col-3 border rounded bg-light">
		<h1><%= t 'welcome' %></h1>
		<p><%= t 'continue'%></p>
		<%=form_with url: session_create_path, method: :post, local:true do |f|%>
			<div>
				<%= f.label :username, style: "display: block"%>
				<%=f.text_field :username, require: true, class: "form-control" %>
			</div>
			<div>
				<%= f.label :password, style:"display: block" %>
				<%=f.password_field :password, require: true, class: "form-control" %>
			</div>
			<div style="margin: 20px 0 20px 0">
				<%=f.submit id: 'submit-btn', value: t('login_btn'),require: true, class: "btn btn-success" %>
			</div>
		<%end%>
		<%unless flash[:notice].blank?%>
			<h2 style = 'color:red'><%= flash[:notice] %></h2>
		<%end%>
		<p><%= t 'have_acc?' %></p>
		<%=link_to t('registr'), new_user_path, class: "link-secondary" %>
    </div>
  </div>
</div>