config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :public_folders
    root 'folders#index'
    #root 'session#login'
    get 'session/login'
    get 'session/logout'
    post 'session/create'
    resources :users
    resources :folders
    resources :tasks
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_uniqueness_of :username
    validates_presence_of :username
    validates_presence_of :password
    validates_confirmation_of :password
    validates_uniqueness_of :email
    validates_presence_of :email
    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: I18n.t("is_invalid") } # email validation
    validates :username, format: { with: /\A(?=.{5,})/x, message: I18n.t("is_short") }

    PASSWORD_FORMAT = /\A
    (?=.{8,})          # Must contain 8 or more characters
    (?=.*\d)           # Must contain a digit
    (?=.*[a-z])        # Must contain a lower case character
    (?=.*[A-Z])        # Must contain an upper case character
    (?=.*[[:^alnum:]]) # Must contain a symbol
    /x
    # validates :password, format: { with: PASSWORD_FORMAT, message: "is not secure. Must contain 8 or more characters" }
    # it works, but I'm too lazy to come up with passwords...

    has_many :folders, dependent: :destroy
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Users Controller
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :check_access, only: %i[show edit update destroy]
  before_action :stay_admin, only: :destroy # cant destroy admin
  skip_before_action :require_login, only: %i[create new]

  # GET /users or /users.json
  def index
    redirect_to root_path unless current_user.id == 6
    @folders = Folder.where(user_id: current_user.id)
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @folders = Folder.where(user_id: current_user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to root_path, notice: t('welcome') }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    @folders = Folder.where(user_id: current_user.id)
    if @user.update(user_params)
      redirect_to user_url(@user), notice: t('user_was_updated')
    elsif !current_user.nil?
      flash[:error] = 'The task title and deadline cannot be empty :('
      # redirect_to user_url(@user) , status: :unprocessable_entity
      render :show, status: :unprocessable_entity
    else
      redirect_to new_user_path, status: :unprocessable_entity
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: t('user_was_destroyed') }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation, :email)
  end

  def check_access
    redirect_to root_path if (current_user.id != 6) && (current_user != set_user)
  end

  def stay_admin
    redirect_to user_path, alert: t('uradmin') if current_user.id == 6
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, t("error")) %></h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username, class: "form-control" %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div style="margin-top: 20px">
    <% btn_title = t('registr') %>
    <% unless current_user.nil? %>
      <% btn_title = t('update') %>
    <% end %>
    <%= form.submit btn_title, id: 'submit-btn', class: "btn btn-success" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
<% cur_folders = Folder.where(user_id: user.id) %>

  <p>
    <strong><%= t 'username' %>: </strong>
    <%= user.username %>
  </p>

  <p>
    <strong><%= t 'email' %>: </strong>
    <%= user.email %>
  </p>

  <p>
    <strong><%= t 'reg_date' %>: </strong>
    <%= user.created_at.to_formatted_s(:db) %>
  </p>

  <p>
    <strong><%= t 'folders_total' %>: </strong>
    <%= cur_folders.count %>
  </p>

  <p>
    <strong><%= t 'tasks_total' %>: </strong>
    <% tasks_total = 0 %>
    <% cur_folders.each do |f| %>
      <% tasks_total += Task.where(folder_id: f.id).count %>
    <% end %>
    <%= tasks_total %> | 

    <strong><%= t 'tasks_completed' %>: </strong>
    <% tasks_done = 0 %>
    <% cur_folders.each do |f| %>
      <% tasks_done += Task.where(folder_id: f.id, done: true).count %>
    <% end %>
    <%= tasks_done %>
  </p>

  <p>
    <strong><%= t 'progress_total' %>: </strong>
    <%= tasks_done %>/<%= tasks_total %>
    <% percent = 0 %>
    <% percent = ((tasks_done / tasks_total.to_f)*100).to_i unless tasks_total.zero? %>
    <div class="progress" style="margin-top: 16px">
      <div class="progress-bar" role="progressbar" style="width: <%= percent %>%; background-color: lightgreen; color: black" aria-valuenow="<%= percent %>" aria-valuemin="0" aria-valuemax="100"><b><%= percent %>%</b></div>
    </div>
  </p>

  <p>
    <strong><%= t 'change_lang' %>: </strong>
    <%= link_to 'EN', user_path(current_user, locale: :en) %>
    <%= link_to 'RU', user_path(current_user, locale: :ru) %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<div class="d-inline-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 15%; height: 100vh; float: left">
  <a href="/<%= locale %>" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
    <span class="fs-6"><%= current_user.username %><%= t 'folders' %></span>
  </a>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <% @folders.each do |folder|%>
    <li>
      <div class="nav-link">
        <%= link_to image_tag('logos/settings-16.png'), url_for("/#{locale}/folders/#{folder.id}/edit"), :class => 'bi me-2', :remote => true %>
        <%= link_to folder.name, folder, style: "color: white; text-decoration: none"%>
      </div>
    </li>
    <% end %>
  </ul>
  <hr>
  <p><%= button_to t("new_folder"), new_folder_path, class: "btn btn-success", method: :get %></p>
</div>

<div class="d-inline-flex flex-column bg-light" style="width: 85%; height: 100vh; overflow: auto">
  <div class="header" style="position: fixed; width: 85%; top: 0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-2" style="height: 125%">
      <div class="container-fluid">
        <img src="https://findicons.com/files/icons/732/snow_leopard/256/folder_folder.png" alt="Logo" style="width: 30px; height: 30px; margin-right: 10px">
        <a class="navbar-brand"><%= t 'user_list' %></a>
        <a class="navbar-brand" style="color: green"><%= notice %></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ms-auto ">
            <li class="nav-item">
              <a class="nav-link mx-2" aria-current="page" href="/<%= locale %>/public_folders"><%= t 'public_tasks' %></a>
            </li>
            <li class="nav-item">
              <a class="nav-link mx-2" aria-current="page" href="/<%= locale %>"><%= t 'my_tasks' %></a>
            </li>
            <% if current_user.id == 6 %>
            <li class="nav-item">
              <a class="nav-link mx-2 active" href="/<%= locale %>/users"><%= t 'all_users' %></a>
            </li>
            <% end %>
            <li class="nav-item">
              <%= link_to t("account"), "/#{locale}/users/#{current_user.id}" , class: "nav-link mx-2"%>
            </li>
            <li class="nav-item">
              <%= link_to t("logout"), session_logout_path, class: "nav-link mx-2" %>
            </li>
          </ul>
        </div> 
      </div>
    </nav>
  </div>

  <div class="row d-flex justify-content-center" style="width: 100%; padding-top: 80px">
    <div class="col-8 border rounded" style="margin: 0 30px 0 30px">
      <h1><%= t 'users' %></h1>
      <hr>

      <div id="users">
        <% @users.each do |user| %>
          <%= render user %>
          <p>
            <%= link_to t('show_user'), user, class: "user_link" %>
          </p>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div id="animated-bg" class="d-inline-flex flex-column bg-light" style="width: 100%; height: 100vh; overflow: auto">
  <div class="header" style="position: fixed; width: 100%; top: 0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-2" style="height: 125%">
      <div class="container-fluid">
        <img src="https://findicons.com/files/icons/732/snow_leopard/256/folder_folder.png" alt="Logo" style="width: 30px; height: 30px; margin-right: 10px">
        <a class="navbar-brand"><%= t 'signup' %></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'EN', root_path(locale: :en), class: "nav-link mx-2" %>
            </li>
            <li class="nav-item">
              <%= link_to 'RU', root_path(locale: :ru), class: "nav-link mx-2" %>
            </li>
          </ul>
          <ul class="navbar-nav ms-auto ">
            <li class="nav-item">
              <a class="nav-link mx-2" aria-current="page" href="/<%= locale %>/session/login"><%= t 'my_tasks' %></a>
            </li>
            <li class="nav-item">
              <%= link_to t("account"), "/#{locale}/session/login" , class: "nav-link mx-2 active"%>
            </li>
            <li class="nav-item">
              <%= link_to t("logout"), session_logout_path, class: "nav-link mx-2" %>
            </li>
          </ul>
        </div> 
      </div>
    </nav>
  </div>

  <div class="row d-flex justify-content-center" style="width: 100%; padding-top: 80px">
    <div class="col-3 border rounded bg-light">
      <h1><%= t 'user_reg' %></h1>
      <%= render "form", user: @user %>
      <br>
      <div>
        <%= link_to t("login"), session_login_path, class: "link-secondary" %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="d-inline-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 15%; height: 100vh; float: left">
  <a href="/<%= locale %>" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
    <span class="fs-6"><%= current_user.username%><%= t 'folders' %></span>
  </a>
  <hr>
  <ul class="nav nav-pills flex-column mb-auto">
    <% @folders.each do |folder|%>
    <li>
      <div class="nav-link">
        <%= link_to image_tag('logos/settings-16.png'), url_for("/#{locale}/folders/#{folder.id}/edit"), :class => 'bi me-2', :remote => true %>
        <%= link_to folder.name, folder, style: "color: white; text-decoration: none"%>
      </div>
    </li>
    <% end %>
  </ul>
  <hr>
  <p><%= button_to t("new_folder"), new_folder_path, class: "btn btn-success", method: :get %></p>
</div>

<div class="d-inline-flex flex-column bg-light" style="width: 85%; height: 100vh; overflow: auto">
  <div class="header" style="position: fixed; width: 85%; top: 0">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-2" style="height: 125%">
      <div class="container-fluid">
        <img src="https://findicons.com/files/icons/732/snow_leopard/256/folder_folder.png" alt="Logo" style="width: 30px; height: 30px; margin-right: 10px">
        <% if current_user.id == 6 %><a class="navbar-brand"><%= @user.username %><%= t 's_account' %></a><% end %>
        <a class="navbar-brand" style="color: green"><%= notice %></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ms-auto ">
            <li class="nav-item">
              <a class="nav-link mx-2" aria-current="page" href="/<%= locale %>/public_folders"><%= t 'public_tasks'%></a>
            </li>
            <li class="nav-item">
              <a class="nav-link mx-2" aria-current="page" href="/<%= locale %>"><%= t 'my_tasks' %></a>
            </li>
            <% if current_user.id == 6 %>
            <li class="nav-item">
              <a class="nav-link mx-2" href="/<%= locale %>/users"><%= t 'all_users' %></a>
            </li>
            <% end %>
            <li class="nav-item">
              <%= link_to t("account"), "/#{locale}/users/#{current_user.id}" , class: "nav-link mx-2 active"%>
            </li>
            <li class="nav-item">
              <%= link_to t("logout"), session_logout_path, class: "nav-link mx-2" %>
            </li>
          </ul>
        </div> 
      </div>
    </nav>
  </div>

  <div class="row d-flex justify-content-center" style="width: 100%; padding-top: 80px">
    <div class="col-3 border rounded" style="margin: 0 30px 0 30px">
      <h1><%= t 'user_info' %></h1>
      <hr>
      <%= render @user %>
    </div>
    <div class="col-4 border rounded" style="margin: 0 30px 0 30px">
      <h1><%= t 'editing' %></h1>
      <hr>
      <%= render "form", user: @user %>
    </div>
    <div class="col-3 border rounded" style="margin: 0 30px 0 30px">
      <h1><%= t 'delete_acc?' %></h1>
      <hr>
      <div style= "margin-top: 20px">
        <%= button_to t("delete_acc"), @user, method: :delete, class: "btn btn-danger" %>
      </div>
      <p style="color: red"><%= flash[:alert] %></p>
    </div>
  </div>
</div>